blank_issues_enabled: false
contact_links:
  - name: 🧑‍💻 Kuukiyomi help discord
    url: https://discord.gg/s82Vu589Ya
    about: Common questions are answered here
  - name: 🖥️ Aniyomi website
    url: https://aniyomi.org/
    about: Guides, troubleshooting, and answers to common questions
