blank_issues_enabled: false
contact_links:
  - name: 🧑‍💻 Aniyomi help discord
    url: https://discord.gg/F32UjdJZrR
    about: Common questions are answered here
  - name: 🖥️ Aniyomi website
    url: https://aniyomi.org/
    about: Guides, troubleshooting, and answers to common questions
