name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Set ACRA properties
        env:
          acraUri: ${{ secrets.ACRA_URI }}
          acraLogin: ${{ secrets.ACRA_LOGIN }}
          acraPassword: ${{ secrets.ACRA_PASSWORD }}
        run: |
          echo "ACRA_URI=$acraUri" >> acra.properties
          echo "ACRA_LOGIN=$acraLogin" >> acra.properties
          echo "ACRA_PASSWORD=$acraPassword" >> acra.properties

      - name: Build app and run unit tests
        uses: gradle/gradle-command-action@v2
        with:
          arguments: ktlintCheck assembleStandardRelease testReleaseUnitTest

      # Sign APK and create release for tags

      - name: Get tag name

        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Dark25/AnimeTail-source'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Dark25/AnimeTail-source'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/standard/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'Dark25/AnimeTail-source'
        run: |
          set -e

          mv app/build/outputs/apk/standard/release/app-standard-universal-release-unsigned-signed.apk animetail-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum animetail-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-arm64-v8a-release-unsigned-signed.apk animetail-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum animetail-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-armeabi-v7a-release-unsigned-signed.apk animetail-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum animetail-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-x86-release-unsigned-signed.apk animetail-x86-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum animetail-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

          cp app/build/outputs/apk/standard/release/app-standard-x86_64-release-unsigned-signed.apk animetail-x86_64-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum animetail-x86_64-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_64_SHA=$sha" >> $GITHUB_ENV

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'animetailorg/animetail'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: animetail ${{ env.VERSION_TAG }}
          body: |
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86 | ${{ env.APK_X86_SHA }}
            | x86_64 | ${{ env.APK_X86_64_SHA }} |
          files: |
            animetail-${{ env.VERSION_TAG }}.apk
            animetail-arm64-v8a-${{ env.VERSION_TAG }}.apk
            animetail-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            animetail-x86-${{ env.VERSION_TAG }}.apk
            animetail-x86_64-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
